### ISSUE TITLE
Internet connection not working

### ISSUE THREAD

**Issue by christopherdumas** [SerenityOS/serenity#79]
I cloned, built, and ran SerenityOS this morning and it doesn't seem to be able to connect to the internet correctly. If I run `ping 127.0.0.1` (localhost) it works, but if I try `ping 8.8.8.8` the request times out and if I attempt `ping google.com` it tells me that the lookup failed:

![2019-05-23-105907_1029x771_scrot](https://user-images.githubusercontent.com/1920151/58275432-de77f980-7d49-11e9-98af-39aae524cee7.png)

I'm not sure what I need to do at this point, I'm assuming its a problem with setting up QEMU? Also, this brings up another thing, when the IRC client can't connect to the internet it just freezes the entire OS, so that's something that needs to be fixed:

![2019-05-23-110134_1270x1406_scrot](https://user-images.githubusercontent.com/1920151/58275551-25fe8580-7d4a-11e9-949c-646539ee9e5c.png)

I planned on contributing to the userland of this OS at first (maybe starting with getting the FileManager forward/back arrows to work: #36, or getting the ProcessManager tree view #65) and then working up to maybe contributing to the more lower level stuff. So if there's something that needs to be fixed here I'd like to help.

**Comment by awesomekling** [comment]
So in order to send ICMP packets from inside QEMU to the outside world, you need to allow the user on your host machine to send ICMP packets. You can enable this by doing:

`echo 1 10000 > /proc/sys/net/ipv4/ping_group_range`

DNS lookups are probably failing because serenity uses a hard-coded address for its DNS server at the moment. Try modifying this line in Servers/LookupServer/main.cpp so it points to the correct DNS server for you instead:

`rc = inet_pton(AF_INET, "127.0.0.53", &dst_addr.sin_addr);`

This is obviously something that should be fixed. :)

It would be good to find out why things are freezing. I've just pushed fba57d6ba3f0b5fc56d01874df2f37a0d21a32c3 which should enable a lot more debug output on everyone's host terminals.

**Comment by christopherdumas** [comment]
Okay so on my system, `/proc/sys/net/ipv4/ping_group_range` doesn't exist? My OS is `Manjaro 18.0.4 Illyria` if it helps. As far as DNS goes, how would I go about finding out what DNS server to use?

**Comment by christopherdumas** [comment]
Okay I ran that command, and now I can ping external IP addresses, but the DNS server still doesn't work. How would I figure out what DNS server to use?
